### ISSUE TITLE
"How to use"

### ISSUE THREAD

**Issue by thomasvanlankveld** [philsturgeon/dbad#34]
I'd like a "how to use" for this licence, like [choosealicence.com](http://choosealicense.com/licenses/mit/) has.

I'm unsure whether to add the "Copyright (C) 2009 Philip Sturgeon me@philsturgeon.uk" bit. The site makes me feel like I should mention Philip Sturgeon as the author of the licence, but when I look at for example the MIT licence, it does not involve mentioning the author of the MIT licence. The MIT licence does involve mentioning yourself, but if I were to try this on DBAD and overwrite the "Philip Sturgeon" bit, I might be violating the DBAD licence myself.

**Comment by philsturgeon** [comment]
Fixed! 97decb907d8d25b0cd3b0054d6c158b19b4058fe 

Thanks for pointing this out. I don't actually remember what the intention was in 2009, but I certainly don't want my name in everyones projects now.

Sorry it took forever to notice this.
